package net.noiamnotarobot.nostalgicversions.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.fabricmc.fabric.api.registry.FuelRegistry;
import net.minecraft.block.Blocks;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.noiamnotarobot.nostalgicversions.NostalgicVersions;
import net.noiamnotarobot.nostalgicversions.block.AlphaBlocks;
import net.noiamnotarobot.nostalgicversions.item.teleporter.TeleporterAlphaItem;
import net.noiamnotarobot.nostalgicversions.item.teleporter.TeleporterModernItem;

public class AlphaItems {
    public static final Item SHOVEL = register("shovel", new ShovelItem(ToolMaterials.IRON, 1, -3.0F, new Item.Settings()));
    public static final Item PICKAXE_STEEL = register("pickaxe_steel", new PickaxeItem(ToolMaterials.IRON, 2, -2.8F, new Item.Settings()));
    public static final Item AXE_STEEL = register("axe_steel", new AxeItem(ToolMaterials.IRON, 3, -3.2F, new Item.Settings()));
    public static final Item STRIKER = register("striker", new AlphaFlintAndSteelItem(new Item.Settings().maxCount(1).maxDamage(64)));
    public static final Item APPLE_RED = register("apple_red", new AlphaFoodItem(new Item.Settings().maxCount(1), 4));
    public static final Item BOW = register("bow", new AlphaBowItem(new Item.Settings().maxCount(1)));
    public static final Item ARROW = register("arrow", new ArrowItem(new Item.Settings()));
    public static final Item COAL = register("coal", new Item(new Item.Settings()), 1600);
    public static final Item DIAMOND = register("diamond", new Item(new Item.Settings()));
    public static final Item INGOT_IRON = register("ingot_iron", new Item(new Item.Settings()));
    public static final Item INGOT_GOLD = register("ingot_gold", new Item(new Item.Settings()));
    public static final Item SWORD_STEEL = Items.IRON_SWORD;
    public static final Item SWORD_WOOD = Items.WOODEN_SWORD;
    public static final Item SHOVEL_WOOD = register("shovel_wood", new ShovelItem(ToolMaterials.WOOD, 1, -3.0F, new Item.Settings()));
    public static final Item PICKAXE_WOOD = register("pickaxe_wood", new PickaxeItem(ToolMaterials.WOOD, 2, -2.8F, new Item.Settings()));
    public static final Item AXE_WOOD = register("axe_wood", new AxeItem(ToolMaterials.WOOD, 3, -3.2F, new Item.Settings()));
    public static final Item SWORD_STONE = Items.STONE_SWORD;
    public static final Item SHOVEL_STONE = register("shovel_stone", new ShovelItem(ToolMaterials.STONE, 1, -3.0F, new Item.Settings()));
    public static final Item PICKAXE_STONE = register("pickaxe_stone", new PickaxeItem(ToolMaterials.STONE, 2, -2.8F, new Item.Settings()));
    public static final Item AXE_STONE = register("axe_stone", new AxeItem(ToolMaterials.STONE, 3, -3.2F, new Item.Settings()));
    public static final Item SWORD_DIAMOND = Items.DIAMOND_SWORD;
    public static final Item SHOVEL_DIAMOND = register("shovel_diamond", new ShovelItem(ToolMaterials.DIAMOND, 1, -3.0F, new Item.Settings()));
    public static final Item PICKAXE_DIAMOND = register("pickaxe_diamond", new PickaxeItem(ToolMaterials.DIAMOND, 2, -2.8F, new Item.Settings()));
    public static final Item AXE_DIAMOND = register("axe_diamond", new AxeItem(ToolMaterials.DIAMOND, 3, -3.2F, new Item.Settings()));
    public static final Item STICK = register("stick", new Item(new Item.Settings()), 100);
    public static final Item BOWL_EMPTY = register("bowl_empty", new Item(new Item.Settings()));
    public static final Item BOWL_SOUP = register("bowl_soup", new AlphaSoupItem(new Item.Settings().maxCount(1), 10));
    public static final Item SWORD_GOLD = Items.GOLDEN_SWORD;
    public static final Item SHOVEL_GOLD = Items.GOLDEN_SHOVEL;
    public static final Item PICKAXE_GOLD = Items.GOLDEN_PICKAXE;
    public static final Item AXE_GOLD = Items.GOLDEN_AXE;
    public static final Item SILK = register("silk", new Item(new Item.Settings()));
    public static final Item FEATHER = register("feather", new Item(new Item.Settings()));
    public static final Item GUNPOWDER = register("gunpowder", new Item(new Item.Settings()));
    public static final Item HOE_WOOD = register("hoe_wood", new AlphaHoeItem(new Item.Settings().maxCount(1), 0));
    public static final Item HOE_STONE = register("hoe_stone", new AlphaHoeItem(new Item.Settings().maxCount(1), 1));
    public static final Item HOE_STEEL = register("hoe_steel", new AlphaHoeItem(new Item.Settings().maxCount(1), 2));
    public static final Item HOE_DIAMOND = register("hoe_diamond", new AlphaHoeItem(new Item.Settings().maxCount(1), 3));
    public static final Item HOE_GOLD = register("hoe_gold", new AlphaHoeItem(new Item.Settings().maxCount(1), 1));
    public static final Item SEEDS = register("seeds", new AlphaSeedsItem(new Item.Settings()));
    public static final Item WHEAT = register("wheat", new Item(new Item.Settings()));
    public static final Item BREAD = register("bread", new AlphaFoodItem(new Item.Settings().maxCount(1), 5));
    public static final Item HELMET_LEATHER = Items.LEATHER_HELMET;
    public static final Item PLATE_LEATHER = Items.LEATHER_CHESTPLATE;
    public static final Item LEGS_LEATHER = Items.LEATHER_LEGGINGS;
    public static final Item BOOTS_LEATHER = Items.LEATHER_BOOTS;
    public static final Item HELMET_CHAIN = Items.CHAINMAIL_HELMET;
    public static final Item PLATE_CHAIN = Items.CHAINMAIL_CHESTPLATE;
    public static final Item LEGS_CHAIN = Items.CHAINMAIL_LEGGINGS;
    public static final Item BOOTS_CHAIN = Items.CHAINMAIL_BOOTS;
    public static final Item HELMET_STEEL = Items.IRON_HELMET;
    public static final Item PLATE_STEEL = Items.IRON_CHESTPLATE;
    public static final Item LEGS_STEEL = Items.IRON_LEGGINGS;
    public static final Item BOOTS_STEEL = Items.IRON_BOOTS;
    public static final Item HELMET_DIAMOND = Items.DIAMOND_HELMET;
    public static final Item PLATE_DIAMOND = Items.DIAMOND_CHESTPLATE;
    public static final Item LEGS_DIAMOND = Items.DIAMOND_LEGGINGS;
    public static final Item BOOTS_DIAMOND = Items.DIAMOND_BOOTS;
    public static final Item HELMET_GOLD = Items.GOLDEN_HELMET;
    public static final Item PLATE_GOLD = Items.GOLDEN_CHESTPLATE;
    public static final Item LEGS_GOLD = Items.GOLDEN_LEGGINGS;
    public static final Item BOOTS_GOLD = Items.GOLDEN_BOOTS;
    public static final Item FLINT = register("flint", new Item(new Item.Settings()));
    public static final Item PORK_RAW = register("pork_raw", new AlphaFoodItem(new Item.Settings().maxCount(1), 3));
    public static final Item PORK_COOKED = register("pork_cooked", new AlphaFoodItem(new Item.Settings().maxCount(1), 8));
    public static final Item PAINTING = Items.PAINTING;
    public static final Item APPLE_GOLD = register("apple_gold", new AlphaFoodItem(new Item.Settings().maxCount(1), 42));
    public static final Item SIGN = Items.OAK_SIGN;
    public static final Item DOOR_WOOD = Items.OAK_DOOR;
    public static final Item BUCKET_EMPTY = register("bucket_empty", new AlphaBucketItem(new Item.Settings().maxCount(1).maxDamage(64), Blocks.AIR));
    public static final Item BUCKET_WATER = register("bucket_water", new AlphaBucketItem(new Item.Settings().maxCount(1).maxDamage(64), Blocks.WATER));
    public static final Item BUCKET_LAVA = register("bucket_lava", new AlphaBucketItem(new Item.Settings().maxCount(1).maxDamage(64), Blocks.LAVA));
    public static final Item MINECART_EMPTY = Items.MINECART;
    public static final Item SADDLE = Items.SADDLE;
    public static final Item DOOR_STEEL = Items.IRON_DOOR;
    public static final Item REDSTONE = Items.REDSTONE;
    public static final Item SNOWBALL = Items.SNOWBALL;
    public static final Item BOAT = Items.OAK_BOAT;
    public static final Item LEATHER = register("leather", new Item(new Item.Settings()));
    public static final Item BUCKET_MILK = register("bucket_milk", new AlphaBucketItem(new Item.Settings().maxCount(1).maxDamage(64), null));
    public static final Item BRICK = register("brick", new Item(new Item.Settings()));
    public static final Item CLAY = register("clay", new Item(new Item.Settings()));
    public static final Item REED = register("reed", new AlphaReedItem(new Item.Settings()));
    public static final Item PAPER = register("paper", new Item(new Item.Settings()));
    public static final Item BOOK = register("book", new Item(new Item.Settings()));
    public static final Item SLIME_BALL = register("slime_ball", new Item(new Item.Settings()));
    public static final Item MINECART_BOX = Items.CHEST_MINECART;
    public static final Item MINECART_ENGINE = Items.FURNACE_MINECART;
    public static final Item EGG = register("egg", new Item(new Item.Settings()));
    public static final Item COMPASS = register("compass", new Item(new Item.Settings()));
    public static final Item FISHING_ROD = register("fishing_rod", new Item(new Item.Settings()));
    public static final Item RECORD_13 = Items.MUSIC_DISC_13;
    public static final Item RECORD_CAT = Items.MUSIC_DISC_CAT;
    public static final Item TELEPORTER_ALPHA = register("teleporter_alpha", new TeleporterAlphaItem(new Item.Settings().maxCount(1)));
    public static final Item TELEPORTER_MODERN = register("teleporter_modern", new TeleporterModernItem(new Item.Settings().maxCount(1)));

    public static final ItemGroup ALPHA_GROUP = FabricItemGroup.builder()
            .icon(() -> new ItemStack(AlphaBlocks.GRASS))
            .displayName(Text.translatable(NostalgicVersions.TranslationKeys.ALPHA_ITEMS))
            .entries(((context, entries) -> {
                entries.add(AlphaBlocks.STONE);
                entries.add(AlphaBlocks.GRASS);
                entries.add(AlphaBlocks.DIRT);
                entries.add(AlphaBlocks.COBBLESTONE);
                entries.add(AlphaBlocks.PLANKS);
                entries.add(AlphaBlocks.SAPLING);
                entries.add(AlphaBlocks.BEDROCK);
                entries.add(AlphaBlocks.SAND);
                entries.add(AlphaBlocks.GRAVEL);
                entries.add(AlphaBlocks.ORE_GOLD);
                entries.add(AlphaBlocks.ORE_IRON);
                entries.add(AlphaBlocks.ORE_COAL);
                entries.add(AlphaBlocks.WOOD);
                entries.add(AlphaBlocks.LEAVES);
                entries.add(AlphaBlocks.SPONGE);
                entries.add(AlphaBlocks.GLASS);
                entries.add(AlphaBlocks.CLOTH);
                entries.add(AlphaBlocks.PLANT_YELLOW);
                entries.add(AlphaBlocks.PLANT_RED);
                entries.add(AlphaBlocks.MUSHROOM_BROWN);
                entries.add(AlphaBlocks.MUSHROOM_RED);
                entries.add(AlphaBlocks.BLOCK_GOLD);
                entries.add(AlphaBlocks.BLOCK_STEEL);
                entries.add(AlphaBlocks.STAIR_SINGLE);
                entries.add(AlphaBlocks.BRICK);
                entries.add(AlphaBlocks.TNT);
                entries.add(AlphaBlocks.BOOKSHELF);
                entries.add(AlphaBlocks.COBBLESTONE_MOSSY);
                entries.add(AlphaBlocks.OBSIDIAN);
                entries.add(AlphaBlocks.TORCH);
                entries.add(AlphaBlocks.FIRE);
                entries.add(AlphaBlocks.MOB_SPAWNER);
                entries.add(AlphaBlocks.STAIR_COMPACT_WOOD);
                entries.add(AlphaBlocks.CHEST);
                entries.add(AlphaBlocks.ORE_DIAMOND);
                entries.add(AlphaBlocks.BLOCK_DIAMOND);
                entries.add(AlphaBlocks.WORKBENCH);
                entries.add(AlphaBlocks.TILLED_FIELD);
                entries.add(AlphaBlocks.STONE_OVEN_IDLE);
                entries.add(AlphaBlocks.LADDER);
                entries.add(AlphaBlocks.MINECART_TRACK);
                entries.add(AlphaBlocks.STAIR_COMPACT_STONE);
                entries.add(AlphaBlocks.LEVER);
                entries.add(AlphaBlocks.PRESSURE_PLATE_STONE);
                entries.add(AlphaBlocks.PRESSURE_PLATE_WOOD);
                entries.add(AlphaBlocks.ORE_REDSTONE);
                entries.add(AlphaBlocks.TORCH_REDSTONE_ACTIVE);
                entries.add(AlphaBlocks.BUTTON);
                entries.add(AlphaBlocks.SNOW);
                entries.add(AlphaBlocks.ICE);
                entries.add(AlphaBlocks.BLOCK_SNOW);
                entries.add(AlphaBlocks.CACTUS);
                entries.add(AlphaBlocks.BLOCK_CLAY);
                entries.add(AlphaBlocks.JUKEBOX);
                entries.add(AlphaBlocks.FENCE);

                entries.add(SHOVEL);
                entries.add(PICKAXE_STEEL);
                entries.add(AXE_STEEL);
                entries.add(STRIKER);
                entries.add(APPLE_RED);
                entries.add(BOW);
                entries.add(ARROW);
                entries.add(COAL);
                entries.add(DIAMOND);
                entries.add(INGOT_IRON);
                entries.add(INGOT_GOLD);
                entries.add(SWORD_STEEL);
                entries.add(SWORD_WOOD);
                entries.add(SHOVEL_WOOD);
                entries.add(PICKAXE_WOOD);
                entries.add(AXE_WOOD);
                entries.add(SWORD_STONE);
                entries.add(SHOVEL_STONE);
                entries.add(PICKAXE_STONE);
                entries.add(AXE_STONE);
                entries.add(SWORD_DIAMOND);
                entries.add(SHOVEL_DIAMOND);
                entries.add(PICKAXE_DIAMOND);
                entries.add(AXE_DIAMOND);
                entries.add(STICK);
                entries.add(BOWL_EMPTY);
                entries.add(BOWL_SOUP);
                entries.add(SWORD_GOLD);
                entries.add(SHOVEL_GOLD);
                entries.add(PICKAXE_GOLD);
                entries.add(AXE_GOLD);
                entries.add(SILK);
                entries.add(FEATHER);
                entries.add(GUNPOWDER);
                entries.add(HOE_WOOD);
                entries.add(HOE_STONE);
                entries.add(HOE_STEEL);
                entries.add(HOE_DIAMOND);
                entries.add(HOE_GOLD);
                entries.add(SEEDS);
                entries.add(WHEAT);
                entries.add(BREAD);
                entries.add(HELMET_LEATHER);
                entries.add(PLATE_LEATHER);
                entries.add(LEGS_LEATHER);
                entries.add(BOOTS_LEATHER);
                entries.add(HELMET_CHAIN);
                entries.add(PLATE_CHAIN);
                entries.add(LEGS_CHAIN);
                entries.add(BOOTS_CHAIN);
                entries.add(HELMET_STEEL);
                entries.add(PLATE_STEEL);
                entries.add(LEGS_STEEL);
                entries.add(BOOTS_STEEL);
                entries.add(HELMET_DIAMOND);
                entries.add(PLATE_DIAMOND);
                entries.add(LEGS_DIAMOND);
                entries.add(BOOTS_DIAMOND);
                entries.add(HELMET_GOLD);
                entries.add(PLATE_GOLD);
                entries.add(LEGS_GOLD);
                entries.add(BOOTS_GOLD);
                entries.add(FLINT);
                entries.add(PORK_RAW);
                entries.add(PORK_COOKED);
                entries.add(PAINTING);
                entries.add(APPLE_GOLD);
                entries.add(SIGN);
                entries.add(DOOR_WOOD);
                entries.add(BUCKET_EMPTY);
                entries.add(BUCKET_WATER);
                entries.add(BUCKET_LAVA);
                entries.add(MINECART_EMPTY);
                entries.add(SADDLE);
                entries.add(DOOR_STEEL);
                entries.add(REDSTONE);
                entries.add(SNOWBALL);
                entries.add(BOAT);
                entries.add(LEATHER);
                entries.add(BUCKET_MILK);
                entries.add(BRICK);
                entries.add(CLAY);
                entries.add(REED);
                entries.add(PAPER);
                entries.add(BOOK);
                entries.add(SLIME_BALL);
                entries.add(MINECART_BOX);
                entries.add(MINECART_ENGINE);
                entries.add(EGG);
                entries.add(COMPASS);
                entries.add(FISHING_ROD);
                entries.add(RECORD_13);
                entries.add(RECORD_CAT);
                entries.add(TELEPORTER_ALPHA);
                entries.add(TELEPORTER_MODERN);
            }))
            .build();

    public static void init() {
        Registry.register(Registries.ITEM_GROUP, NostalgicVersions.Util.id("alpha_items"), ALPHA_GROUP);
    }

    public static Item register(String name, Item item) {
        return Registry.register(Registries.ITEM, NostalgicVersions.Util.id(name), item);
    }

    public static Item register(String name, Item item, int fuelTime) {
        FuelRegistry.INSTANCE.add(item, fuelTime);
        return register(name, item);
    }
}
